[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.20"

# Exclude test and lib folders
test = "contracts/test"
script = "contracts/script"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/"
]

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"
